version: "3"
services:
  backend:
    build: ./backend
    image: backend
    container_name: backend
    ports:
      - 8000:8000
    volumes:
      - .:/app
    tty: true
    networks:
      - main_network

networks:
  main_network:
    driver: bridge