# Generated by Django 4.2.16 on 2024-11-13 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecyclingStorageHistory',
            fields=[
                (
                    'basemodel_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='app.basemodel',
                    ),
                ),
                ('capacity', models.FloatField(default=0.0)),
                (
                    'recycling_storage',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='history',
                        to='app.recyclingstorage',
                    ),
                ),
            ],
            bases=('app.basemodel',),
        ),
    ]
